# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
  languageCode: zh-Hans
  title: 微纳光电集成研究团队
  params:
    description: 南京邮电大学微纳光电集成研究团队
